### ISSUE TITLE
About strategy of deployment

### ISSUE THREAD

**Issue by vision9527** [profefe/profefe#126]
Hello bro, I have one question.
I will just start collector in one machine when I use badger as storage, because badger is not distributed storage?
Is right? What should I do if I want to deploy cluster of collector?

**Comment by narqo** [comment]
There are different options to scale when using badger storage. What is the main goal of the cluster in your use case: do you target high-availability, or do you need to scale out?

Collector's API is plain HTTP. Consider starting a set of individual collectors and set up a proxy in front of them. E.g. with HAProxy one can build high-available cluster of collectors, sending the writes to several nodes while balancing the reads to any or nodes.
