### ISSUE TITLE
Add example project

### ISSUE THREAD

**Issue by narqo** [profefe/profefe#13]
[Google's "Hipster Shop"][1] might be a good candidate project. One needs to fork it and replace Stackdriver's agent with `profefe/agent`.

[1]: https://github.com/GoogleCloudPlatform/microservices-demo

**Comment by karuppiah7890** [comment]
I can see example project here https://github.com/profefe/profefe/tree/master/examples , so this issue is done and can be closed now?

**Comment by narqo** [comment]
I think you are right, the current examples should be simple enough to illustrate the usage. We can add more sophisticated examples on request.
