### ISSUE TITLE
Go mod migration

### ISSUE THREAD

**Issue by gianarb** [profefe/profefe#38]
Hello
Thanks for this nice project.
Do you have any plan to migrate it to `go mod`?
Thanks

**Comment by narqo** [comment]
I haven't carefully thought about that. The thing that isn't clear to me is if `profefe/agent` should be a separate module, as I expect a user wouldn't want to see all profefe's transitive dependencies in here project (like one doesn't need to depend on collector's badger or zap to use agent).
