### ISSUE TITLE
Response after creation

### ISSUE THREAD

**Issue by gianarb** [profefe/profefe#41]
Hello

I am writing a bit of code around profefe and I would like to return a usable link or at least the profile ID for the current submitted one.

Currently after the profile submission returns only `{"code":200}`. Are you against the possibility to return at least its ID?

**Comment by narqo** [comment]
I think it's a good opportunity to unify JSON responses between "create" and "list" endpoints. What do you think if both endpoints returned the structure:

```
{
  "code": 200,
  "data": <response_data>
}
```

where `response_data` is created profile meta and the list of queried metas.

**Comment by gianarb** [comment]
It sounds good to me!

Il Mer 27 Nov 2019, 17:20 Vladimir Varankin <notifications@github.com> ha
scritto:
