### ISSUE TITLE
S3 profile ID does not look right

### ISSUE THREAD

**Issue by gianarb** [profefe/profefe#80]
Hello,

S3 should work as the other storage.

S3 profile ID P0.service/4/bq0rups0s6cfii5dn030,from=label,label2=label2

For the other storage: bq0rups0s6cfii5dn030

This ID is complicated because this does not work:

```
go tool pprof http://localhost:10100/api/0/profiles/P0.service/4/bq0rups0s6cfii5dn030,from=label,label2=label2
```

I am not sure what changed but the implementation we hacked here https://github.com/profefe/profefe/pull/52 were working as expected

**Comment by gianarb** [comment]
`4` is the type if I am well reading the code. So with this format, I can lookup by ID because I always need to pass the profile type

**Comment by narqo** [comment]
`P0.service/4/bq0rups0s6cfii5dn030,from=label,label2=label2` is the ID of the object stored on S3 and we use it as the ID of the profile. Note, the implementation in #69 is different from what was proposed in #52 by what we use as profile ID.

Can I ask if the profile you're reading were stored by the upstream version of profefe or those are from the S3 storage implemented in the fork (i.e. #52)? The former means there is a bug; the 
later means you either need to convert the old IDs into the new schema (I can help with writing a script for that), or we need to think about how to support these old IDs for reads.

**Comment by gianarb** [comment]
I am trying to make the one upstream #69 to work

This is what I have in my s3 bucket:

```
$ aws s3 ls s3://bucket/P0.pod/6/bq1095kgirkag7l0g4f0,from=kube-profefe,namespace=ns,pod=pod-rmglc
```

But when I do  

```
$ aws s3 ls s3://bucket/profiles/bq1095kgirkag7l0g4f0
```

The object is not there

**Comment by narqo** [comment]
> This is what I have in my s3 bucket:
> ```
> $ aws s3 ls s3://bucket/P0.pod/6/bq1095kgirkag7l0g4f0,from=kube-profefe,namespace=ns,pod=pod-rmglc
> ```

Yeah, that the expected object. The request to `/api/0/profiles/P0.pod/6/bq1095kgirkag7l0g4f0,from=kube-profefe,namespace=ns,pod=pod-rmglc` expected to retrieve it.

I will have a look shortly.

**Comment by gianarb** [comment]
Thank you. I am not sure if I am using the API wrong or something is not working.

My expectation is to get the same workflow I use with badge.

So the ID returned by the API should be a single string the digest. And it should be used to lookup a single profile.

**Comment by gianarb** [comment]
Ok I can close this issue because this is not a real issue it is working as expected. The ID is just very uncommon. I will open a new issue to discuss it
