### ISSUE TITLE
storage/postgres: Schema migrations

### ISSUE THREAD

**Issue by narqo** [profefe/profefe#9]
As for now each change in Postgres's SQL schema required starting DB from scratch. That's okay for the earlier prototyping phase, but something that must be addressed in future.

One needs to investigate how SQL schema migration is typically handled in a Go project.

*Check me*:

- https://github.com/heroiclabs/nakama/tree/master/migrate
- https://github.com/sourcegraph/sourcegraph/tree/master/migrations

**Comment by Slach** [comment]
FYI https://github.com/golang-migrate/migrate

**Comment by narqo** [comment]
Thank you for the link. After #28 where I've retired `storage/postgres` in favour of `storage/badger` (see the motivation in PR's description), this issue isn't actionable anymore.
